# Generated by Django 5.0.6 on 2025-01-20 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badger", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("total_steps", models.IntegerField(default=1)),
                ("category", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="BadgeProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repository_name", models.CharField(max_length=255)),
                ("student_username", models.CharField(max_length=255)),
                ("current_step", models.IntegerField(default=0)),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="gradecheck",
            name="course",
        ),
        migrations.RemoveIndex(
            model_name="gradecheck",
            name="badger_grad_reposit_97d464_idx",
        ),
        migrations.RemoveIndex(
            model_name="gradecheck",
            name="badger_grad_workflo_6062d5_idx",
        ),
        migrations.RemoveIndex(
            model_name="gradecheck",
            name="badger_grad_course__cc5f2e_idx",
        ),
        migrations.RenameField(
            model_name="gradecheck",
            old_name="check_details",
            new_name="check_results",
        ),
        migrations.RemoveField(
            model_name="gradecheck",
            name="assignment_name",
        ),
        migrations.AddField(
            model_name="badgeprogress",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="badger.badge"
            ),
        ),
        migrations.DeleteModel(
            name="Course",
        ),
        migrations.AlterUniqueTogether(
            name="badgeprogress",
            unique_together={("badge", "repository_name", "student_username")},
        ),
    ]
