# Generated by Django 5.0.6 on 2025-01-20 16:56

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("badger", "0002_badge_badgeprogress_remove_gradecheck_course_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="gradecheck",
            name="update_badge_status",
        ),
        migrations.RenameField(
            model_name="gradecheck",
            old_name="check_results",
            new_name="check_details",
        ),
    ]
