# Generated by Django 5.0.6 on 2025-01-21 15:14

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("badger", "0003_remove_gradecheck_update_badge_status_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="GradeCheck",
            new_name="GatorCheck",
        ),
        migrations.RemoveField(
            model_name="badgeprogress",
            name="current_step",
        ),
        migrations.AddField(
            model_name="badge",
            name="badge_id",
            field=models.CharField(default="BADGE_DEFAULT", max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name="badgeprogress",
            name="step_status",
            field=models.JSONField(default=dict),
        ),
        migrations.AddIndex(
            model_name="badgeprogress",
            index=models.Index(
                fields=["student_username", "repository_name"],
                name="badger_badg_student_89186e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="badgeprogress",
            index=models.Index(
                fields=["badge", "completed"], name="badger_badg_badge_i_e1513d_idx"
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="gatorcheck",
            trigger=pgtrigger.compiler.Trigger(
                name="update_check_status",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func="\n            BEGIN\n                IF NEW.passed_checks = NEW.total_checks THEN\n                    NEW.status := 'passed';\n                ELSE\n                    NEW.status := 'failed';\n                END IF;\n                RETURN NEW;\n            END;\n        ",
                    hash="411753bba7eac2acaa58e538b4874bad9b17ee00",
                    operation="UPDATE OR INSERT",
                    pgid="pgtrigger_update_check_status_03e92",
                    table="badger_gatorcheck",
                    when="AFTER",
                ),
            ),
        ),
    ]
