# Generated by Django 5.1.6 on 2025-03-24 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("persona", "0005_personamodel_asssistant_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="personamodel",
            old_name="asssistant_owner",
            new_name="assistant_owner",
        ),
    ]
