name: Publish release
on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.12
      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install --only-upgrade python3-pip
          sudo python -m pip install -e .
          sudo python -m pip install -r docs/requirements.txt
          cd docs && make html
      - name: Setup Pages
        uses: actions/configure-pages@v5.0.0
      - name: Create release
        id: create_release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name}}
      - name: Upload rendered docs
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: ./docs/build/html
        if: always()
  deploy-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: publish
    steps:
      - name: Deploy Github Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5
